CREATE TABLE `USUARIOS` (
  `USUARIOS_ID` INT NOT NULL AUTO_INCREMENT,
  `LOGIN` VARCHAR(45) NULL,
  `PWD` VARCHAR(250) NULL,
  `NOMBRE_COMPLETO` VARCHAR(150) NULL,
  `ESTADO` TINYINT(1) NULL,
  PRIMARY KEY (`USUARIOS_ID`),
  UNIQUE INDEX `LOGIN_UNIQUE` (`LOGIN` ASC));

INSERT INTO `USUARIOS` (`LOGIN`, `PWD`, `NOMBRE_COMPLETO`, `ESTADO`) VALUES 
('pruebas', 'Sm55bEt5TjUzQmRCVm1OTFRLQmlBUT09', 'Juan Nicolas Hernandez Duque', '1');


CREATE TABLE `PROC_PROCESO` (
  `PRO_ID` INT NOT NULL AUTO_INCREMENT,
  `PRO_NAME` VARCHAR(150) NULL,
  `PRO_PREFIJO` VARCHAR(10) NULL,
  PRIMARY KEY (`PRO_ID`));

INSERT INTO `PROC_PROCESO` (`PRO_NAME`, `PRO_PREFIJO`) VALUES 
('Ingenieria', 'ING'),
('Desarrollo', 'DES'),
('Planeacion', 'PLA'),
('Construccion', 'CON'),
('Entrega', 'ENT');


CREATE TABLE `TIP_TIPO_DOC` (
  `TIP_ID` INT NOT NULL AUTO_INCREMENT,
  `TIP_NOMBRE` VARCHAR(45) NULL,
  `TIP_PREFIJO` VARCHAR(10) NULL,
  PRIMARY KEY (`TIP_ID`));

INSERT INTO `TIP_TIPO_DOC` (`TIP_NOMBRE`, `TIP_PREFIJO`) VALUES 
('Instructivo', 'INS'),
('Guia', 'GUI'),
('Folleto', 'FOL'),
('Capacitacion', 'CAP'),
('Manual', 'MAN');


CREATE TABLE `DOC_DOCUMENTO` (
  `DOC_ID` INT NOT NULL AUTO_INCREMENT,
  `DOC_NOMBRE` VARCHAR(100) NULL,
  `DOC_CODIGO` VARCHAR(45) NULL,
  `DOC_CONTENIDO` LONGTEXT NULL,
  `DOC_ID_TIPO` INT NULL,
  `DOC_ID_PROCESO` INT NULL,
  PRIMARY KEY (`DOC_ID`),
  INDEX `DOC_ID_TIPO_FK_idx` (`DOC_ID_TIPO` ASC),
  CONSTRAINT `DOC_ID_TIPO_FK`
    FOREIGN KEY (`DOC_ID_TIPO`)
    REFERENCES `TIP_TIPO_DOC` (`TIP_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  INDEX `DOC_ID_PROCESO_FK_idx` (`DOC_ID_PROCESO` ASC),
  CONSTRAINT `DOC_ID_PROCESO_FK`
    FOREIGN KEY (`DOC_ID_PROCESO`)
    REFERENCES `PROC_PROCESO` (`PRO_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);